config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post "users/login" => "users#login"
  get "users/login" => "users#showlogin"
  get "users/createcomp" => "users#createcomp"

  post "users/logout" => "users#logout"
  get "users/logout" => "users#showlogout"


  resources :users

  get "/" => "home#top"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :password, presence: true
  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  def authenticate_user
    if @current_user == nil
      flash[:notice] = "ログインが必要です"
      redirect_to(users_login_path)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:index,:show,:edit,:update,:destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        NotificationMailer.send_confirm_to_user(@user).deliver
        format.html { redirect_to users_createcomp_path , notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def createcomp
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def showlogin
  end

  def login
    @login_user = User.find_by(name: params[:name])
    respond_to do |format|
      if @login_user && @login_user.authenticate(params[:password])
        session[:user_id] = @login_user.id
        format.html { redirect_to users_path }
      else
        format.html { render :showlogin }
        flash[:alert] = "ユーザ名orパスワードが間違っています。"
      end
    end
  end

  def showlogout
  end

  def logout
    session[:user_id] = nil
    flash[:notic] = "ログアウトしました"
    redirect_to(users_logout_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<h1>top</h1>
<h3><%= link_to("Signup",new_user_path) %></h3>
<h3><%= link_to("Login", users_login_path) %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/login/show.html.erb
<h1>login</h1>

<%= form_with( url: login_login_path, local: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :password, "パスワード" %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit :login %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class=”form-group”>
      <%= form.label :name, "名前" %>
      <%= form.text_field :name, :class => 'form-control' %>
    </div>

    <div class=”form-group”>
      <%= form.label :email, "メール" %>
      <%= form.text_field :email, :class => 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :password, "パスワード" %>
      <%= form.password_field :password, :class => 'form-control' ,value: "sss"%>
    </div>

    <div class="form-group">
      <%= form.label :password_confirmation, "パスワードの再入力" %>
      <%= form.password_field :password_confirmation, :class => 'form-control',value:"sss" %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/users/createcomp.html.erb
<h3>新規登録が完了しました。</h3>
<h3><%= link_to("ログイン",users_login_path) %></h3>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

<p><%= link_to("ログアウト", users_logout_path ,{method: :post}) %></p>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/showlogin.html.erb
<% if flash[:notice] %>
  <h3><%= flash[:notice] %></h3>
<% end %>
<h1>login</h1>
<%= form_with( url: users_login_path, local: true) do |form| %>

  <% if flash[:alert] %>
    <div id="error_explanation">
      <h2>prohibited this user from being saved:</h2>

      <ul>
      <%= flash[:alert] %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "名前" %>
    <%= form.text_field :name, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :password, "パスワード" %>
    <%= form.password_field :password, :class => 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit :login %>
  </div>
<% end %>

app/views/users/showlogout.html.erb
<h3><%= flash[:notic] %></h3>
<h3><%= link_to("Topに戻る","/") %></h3>